import type { Tool } from '@/types';

export const tools: Tool[] = [
  // MOST POPULAR TOOLS
  {
    slug: 'qr-code-generator',
    title: 'QR Code Generator',
    description: 'Create custom QR codes instantly. Free, unlimited, no signup. URLs, text, email, phone, WiFi and more.',
    icon: '📱',
    category: 'Most Popular',
    isAI: false,
    isPopular: true,
    path: '/tools/qr-code-generator/index.html',
  },
  {
    slug: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate unique UUIDs (v4) instantly. Perfect for databases, testing, and development.',
    icon: '🆔',
    category: 'Most Popular',
    isAI: false,
    isPopular: true,
    path: '/tools/uuid-generator/index.html',
  },
  {
    slug: 'url-shortener',
    title: 'URL Shortener',
    description: 'Shorten long URLs into clean, shareable links. Track clicks and manage your shortened URLs.',
    icon: '🔗',
    category: 'Most Popular',
    isAI: false,
    isPopular: true,
    path: '/tools/url-shortener/index.html',
  },
  {
    slug: 'color-converter',
    title: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and CMYK. Color picker and complementary colors.',
    icon: '🎨',
    category: 'Most Popular',
    isAI: false,
    isPopular: true,
    path: '/tools/color-converter/index.html',
  },
  {
    slug: 'bulk-qr-code-generator',
    title: 'Bulk QR Code Generator',
    description: 'Generate 1-50 QR codes at once. Download all as ZIP. Multiple content types supported.',
    icon: '📱',
    category: 'Most Popular',
    isAI: false,
    isPopular: true,
    path: '/tools/bulk-qr-code-generator/index.html',
  },
  {
    slug: 'bulk-url-shortener',
    title: 'Bulk URL Shortener',
    description: 'Shorten 1-50 URLs in batch. Download as CSV/TXT. Choose your shortener service.',
    icon: '🔗',
    category: 'Most Popular',
    isAI: false,
    isPopular: true,
    path: '/tools/bulk-url-shortener/index.html',
  },

  // UTILITY TOOLS
  {
    slug: 'ip-location-finder',
    title: 'IP Location Finder',
    description: 'Find location details from IP address. Country, city, ISP, timezone lookup.',
    icon: '🌍',
    category: 'Utility',
    isAI: false,
    path: '/tools/ip-location-finder/index.html',
  },
  {
    slug: 'user-agent-parser',
    title: 'User Agent Parser',
    description: 'Parse browser user agent strings. Detect browser, OS, and device information.',
    icon: '🖥️',
    category: 'Utility',
    isAI: false,
    path: '/tools/user-agent-parser/index.html',
  },
  {
    slug: 'link-preview-generator',
    title: 'Link Preview Generator',
    description: 'Generate link previews with title, description, and images from any URL.',
    icon: '🔗',
    category: 'Utility',
    isAI: false,
    path: '/tools/link-preview-generator/index.html',
  },
  {
    slug: 'url-expander',
    title: 'URL Expander',
    description: 'Expand shortened URLs and check redirect chains. Safety check for malicious links.',
    icon: '🔓',
    category: 'Utility',
    isAI: false,
    path: '/tools/url-expander/index.html',
  },
  {
    slug: 'ifsc-validator',
    title: 'IFSC Validator',
    description: 'Validate Indian IFSC codes. Get bank name, branch, address, and contact details.',
    icon: '🏦',
    category: 'Utility',
    isAI: false,
    path: '/tools/ifsc-validator/index.html',
  },
  {
    slug: 'eu-vat-validator',
    title: 'EU VAT Validator',
    description: 'Validate EU VAT numbers instantly. Check company name and address.',
    icon: '🇪🇺',
    category: 'Utility',
    isAI: false,
    path: '/tools/eu-vat-validator/index.html',
  },
  {
    slug: 'company-lookup',
    title: 'Company Lookup',
    description: 'Get company information by domain. Size, industry, location, revenue, and more.',
    icon: '🏢',
    category: 'Utility',
    isAI: false,
    path: '/tools/company-lookup/index.html',
  },
  {
    slug: 'email-signature-generator',
    title: 'Email Signature Generator',
    description: 'Design professional HTML email signatures. Customizable templates, instant download.',
    icon: '🖊️',
    category: 'Utility',
    isAI: false,
    path: '/tools/email-signature-generator/index.html',
  },
  {
    slug: 'text-to-pdf-converter',
    title: 'Text to PDF Converter',
    description: 'Convert plain text or formatted notes into a clean, professional PDF document instantly.',
    icon: '📝',
    category: 'Utility',
    isAI: false,
    path: '/tools/text-to-pdf-converter/index.html',
  },
  {
    slug: 'pdf-carousel-maker',
    title: 'PDF Carousel Maker',
    description: 'Design and download LinkedIn PDF carousels instantly. Multiple templates available.',
    icon: '🎠',
    category: 'Utility',
    isAI: false,
    path: '/tools/pdf-carousel-maker/index.html',
  },
  {
    slug: 'website-color-extractor',
    title: 'Website Color Extractor',
    description: 'Extract color palette from any website URL. Get dominant colors with HEX and RGB values.',
    icon: '🎨',
    category: 'Utility',
    isAI: false,
    path: '/tools/website-color-extractor/index.html',
  },
  {
    slug: 'what-is-my-ip',
    title: 'What Is My IP',
    description: 'Find your IP address instantly. Get IPv4, IPv6, location details, ISP, and more with one click.',
    icon: '🌐',
    category: 'Utility',
    isAI: false,
    path: '/tools/what-is-my-ip/index.html',
  },
  {
    slug: 'browser-detector',
    title: 'Browser Detector',
    description: 'Detect your browser name, version, OS, device type, and screen resolution instantly.',
    icon: '🖥️',
    category: 'Utility',
    isAI: false,
    path: '/tools/browser-detector/index.html',
  },
  {
    slug: 'network-diagnostics',
    title: 'Network Diagnostics',
    description: 'Test your network connection speed, ping, DNS lookup, and network type with detailed analysis.',
    icon: '📡',
    category: 'Utility',
    isAI: false,
    path: '/tools/network-diagnostics/index.html',
  },
  {
    slug: 'http-header-inspector',
    title: 'HTTP Header Inspector',
    description: 'Inspect HTTP headers of any URL. View security headers, response codes, and export as JSON.',
    icon: '🔎',
    category: 'Utility',
    isAI: false,
    path: '/tools/http-header-inspector/index.html',
  },
  {
    slug: 'robot-avatar-generator',
    title: 'Robot Avatar Generator',
    description: 'Generate unique robot avatars from names or emails. Multiple styles, download as PNG.',
    icon: '🤖',
    category: 'Utility',
    isAI: false,
    path: '/tools/robot-avatar-generator/index.html',
  },
  {
    slug: 'bulk-uuid-generator',
    title: 'Bulk UUID Generator',
    description: 'Generate 1-1000 UUIDs at once. Support for v1, v4, v5. Copy or download as TXT/CSV.',
    icon: '🆔',
    category: 'Utility',
    isAI: false,
    path: '/tools/bulk-uuid-generator/index.html',
  },
  {
    slug: 'image-compressor',
    title: 'Image Compressor',
    description: 'Compress images without losing quality. Support for JPG, PNG, WebP formats.',
    icon: '🖼️',
    category: 'Utility',
    isAI: false,
    path: '/tools/image-compressor/index.html',
  },
  {
    slug: 'email-validity-checker',
    title: 'Email Validity Checker',
    description: 'Verify if an email address is real, disposable, or invalid.',
    icon: '🛡️',
    category: 'Utility',
    isAI: false,
    path: '/tools/email-validity-checker/index.html',
  },
  {
    slug: 'phone-spam-checker',
    title: 'Phone Spam Checker',
    description: 'Check if a phone number is flagged as spam or invalid.',
    icon: '🚫',
    category: 'Utility',
    isAI: false,
    path: '/tools/phone-spam-checker/index.html',
  },
  {
    slug: 'company-buying-power-checker',
    title: 'Company Buying Power Checker',
    description: 'Estimate a company\'s budget and purchasing ability based on public data.',
    icon: '🏢',
    category: 'Utility',
    isAI: false,
    path: '/tools/company-buying-power-checker/index.html',
  },

  // CALCULATORS
  {
    slug: 'cpl-calculator',
    title: 'CPL Calculator',
    description: 'Calculate your true Cost Per Lead based on ad spend. Essential for marketing ROI.',
    icon: '💵',
    category: 'Calculators',
    isAI: false,
    path: '/tools/cpl-calculator/index.html',
  },
  {
    slug: 'roas-quick-checker',
    title: 'ROAS Quick Checker',
    description: 'Instantly compute your Return On Ad Spend. Track campaign profitability.',
    icon: '🚀',
    category: 'Calculators',
    isAI: false,
    path: '/tools/roas-quick-checker/index.html',
  },
  {
    slug: 'chatbot-roi-calculator',
    title: 'Chatbot ROI Calculator',
    description: 'Calculate potential savings and ROI of using AI chatbots for customer support.',
    icon: '💰',
    category: 'Calculators',
    isAI: false,
    path: '/tools/chatbot-roi-calculator/index.html',
  },
  {
    slug: 'whatsapp-response-time-calculator',
    title: 'WhatsApp Response Time Calculator',
    description: 'Track and calculate your average WhatsApp response times. Improve customer satisfaction.',
    icon: '⏱️',
    category: 'Calculators',
    isAI: false,
    path: '/tools/whatsapp-response-time-calculator/index.html',
  },
  {
    slug: 'chat-engagement-scorer',
    title: 'Chat Engagement Scorer',
    description: 'Score leads based on their WhatsApp interaction levels. Prioritize hot leads.',
    icon: '⭐',
    category: 'Calculators',
    isAI: true,
    path: '/tools/chat-engagement-scorer/index.html',
  },
  {
    slug: 'lead-follow-up-gap-finder',
    title: 'Lead Follow-up Gap Finder',
    description: 'Identify missed follow-ups and re-engagement opportunities. Never lose a lead.',
    icon: '🔍',
    category: 'Calculators',
    isAI: false,
    path: '/tools/lead-follow-up-gap-finder/index.html',
  },
  {
    slug: 'carbon-footprint-calculator',
    title: 'Carbon Footprint Calculator',
    description: 'Calculate your CO2 emissions from daily activities. Get personalized tips to reduce footprint.',
    icon: '🌍',
    category: 'Calculators',
    isAI: false,
    path: '/tools/carbon-footprint-calculator/index.html',
  },
  {
    slug: 'math-equation-solver',
    title: 'Math Equation Solver',
    description: 'Solve algebra, calculus, and trigonometry equations with step-by-step solutions and graphs.',
    icon: '🧮',
    category: 'Calculators',
    isAI: false,
    path: '/tools/math-equation-solver/index.html',
  },

  // SITEMAP TOOLS
  {
    slug: 'sitemap-finder-checker',
    title: 'Sitemap Finder & Checker',
    description: 'Quickly find and check the validity of XML sitemaps for any website.',
    icon: '🔍',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-finder-checker/index.html',
  },
  {
    slug: 'sitemap-validator',
    title: 'Sitemap Validator',
    description: 'Validate your sitemap against XML schema standards. Ensure SEO compliance.',
    icon: '✅',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-validator/index.html',
  },
  {
    slug: 'xml-sitemap-generator',
    title: 'XML Sitemap Generator',
    description: 'Generate standard XML sitemaps for your website. SEO-ready format.',
    icon: '⚙️',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/xml-sitemap-generator/index.html',
  },
  {
    slug: 'sitemap-url-extractor',
    title: 'Sitemap URL Extractor',
    description: 'Extract all URLs from a given sitemap easily. Export to CSV or TXT.',
    icon: '📋',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-url-extractor/index.html',
  },
  {
    slug: 'sitemap-urls-comparison-tool',
    title: 'Sitemap URLs Comparison Tool',
    description: 'Compare two sitemaps to find added or missing URLs. Track changes over time.',
    icon: '⚖️',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-urls-comparison-tool/index.html',
  },
  {
    slug: 'sitemap-split-merger-tool',
    title: 'Sitemap Split/Merger Tool',
    description: 'Split large sitemaps or merge smaller ones. Manage sitemap size efficiently.',
    icon: '✂️',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-split-merger-tool/index.html',
  },
  {
    slug: 'sitemap-analytics-insights',
    title: 'Sitemap Analytics & Insights',
    description: 'Get detailed analytics about your sitemap structure. URL counts, update frequency.',
    icon: '📊',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-analytics-insights/index.html',
  },
  {
    slug: 'sitemap-index-generator',
    title: 'Sitemap Index Generator',
    description: 'Generate a sitemap index file for multiple sitemaps. Organize large sites.',
    icon: '🗂️',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-index-generator/index.html',
  },
  {
    slug: 'sitemap-to-robots-txt-generator',
    title: 'Sitemap to Robots.txt Generator',
    description: 'Generate robots.txt entries for your sitemaps. Proper crawler directives.',
    icon: '🤖',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-to-robots-txt-generator/index.html',
  },
  {
    slug: 'sitemap-frequency-analyzer',
    title: 'Sitemap Frequency Analyzer',
    description: 'Analyze the update frequency defined in your sitemaps. Optimize crawl budget.',
    icon: '⏱️',
    category: 'Sitemap',
    isAI: false,
    path: '/tools/sitemap-frequency-analyzer/index.html',
  },

  // CONVERTERS
  {
    slug: 'convert-csv-to-markdown',
    title: 'CSV to Markdown',
    description: 'Turn CSV data into perfectly formatted Markdown tables instantly.',
    icon: '📊',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-csv-to-markdown/index.html',
  },
  {
    slug: 'convert-json-to-markdown',
    title: 'JSON to Markdown',
    description: 'Convert JSON structures into readable Markdown documentation.',
    icon: '🧩',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-json-to-markdown/index.html',
  },
  {
    slug: 'convert-html-to-markdown',
    title: 'HTML to Markdown',
    description: 'Parse HTML and output clean Markdown syntax. Perfect for content migration.',
    icon: '🌐',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-html-to-markdown/index.html',
  },
  {
    slug: 'convert-paste-to-markdown',
    title: 'Convert Paste to Markdown',
    description: 'Paste rich text and get instant Markdown code. No formatting lost.',
    icon: '📋',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-paste-to-markdown/index.html',
  },
  {
    slug: 'convert-webpage-to-markdown',
    title: 'Convert Webpage to Markdown',
    description: 'Enter a URL to get the page\'s content as Markdown. Great for archiving.',
    icon: '🖥️',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-webpage-to-markdown/index.html',
  },
  {
    slug: 'convert-pdf-to-markdown',
    title: 'Convert PDF to Markdown',
    description: 'Extract text from PDFs and convert to clean Markdown format.',
    icon: '📄',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-pdf-to-markdown/index.html',
  },
  {
    slug: 'convert-docx-to-markdown',
    title: 'Convert DOCX to Markdown',
    description: 'Convert Word documents to Markdown while preserving formatting.',
    icon: '📘',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-docx-to-markdown/index.html',
  },
  {
    slug: 'convert-rtf-to-markdown',
    title: 'Convert RTF to Markdown',
    description: 'Convert Rich Text Format files to clean Markdown.',
    icon: '📝',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-rtf-to-markdown/index.html',
  },
  {
    slug: 'convert-xml-to-markdown',
    title: 'Convert XML to Markdown',
    description: 'Transform XML data into readable Markdown documentation.',
    icon: '📄',
    category: 'Converters',
    isAI: false,
    path: '/tools/convert-xml-to-markdown/index.html',
  },
  {
    slug: 'currency-converter',
    title: 'Currency Converter',
    description: 'Convert between world currencies with real-time exchange rates.',
    icon: '💱',
    category: 'Converters',
    isAI: false,
    path: '/tools/currency-converter/index.html',
  },
  {
    slug: 'historical-currency-converter',
    title: 'Historical Currency Converter',
    description: 'Get exchange rates from any past date. Compare historical and current rates with charts.',
    icon: '📅',
    category: 'Converters',
    isAI: false,
    path: '/tools/historical-currency-converter/index.html',
  },
  {
    slug: 'currency-trend-analyzer',
    title: 'Currency Trend Analyzer',
    description: 'Analyze 30/60/90 day currency trends. View charts, statistics, and predictions.',
    icon: '📈',
    category: 'Converters',
    isAI: false,
    path: '/tools/currency-trend-analyzer/index.html',
  },
  {
    slug: 'color-harmony-checker',
    title: 'Color Harmony Checker',
    description: 'Generate beautiful color palettes. Complementary, analogous, triadic harmonies with export.',
    icon: '🎨',
    category: 'Converters',
    isAI: false,
    path: '/tools/color-harmony-checker/index.html',
  },

  // ANALYTICS TOOLS
  {
    slug: 'wikipedia-popularity-checker',
    title: 'Wikipedia Popularity Checker',
    description: 'Check Wikipedia article page views for the last 30, 60, or 90 days. Compare multiple articles.',
    icon: '📄',
    category: 'Analytics',
    isAI: false,
    path: '/tools/wikipedia-popularity-checker/index.html',
  },
  {
    slug: 'app-store-analyzer',
    title: 'App Store Analyzer',
    description: 'Analyze iOS apps from the App Store. Get ratings, reviews, pricing, and competitor insights.',
    icon: '📱',
    category: 'Analytics',
    isAI: true,
    path: '/tools/app-store-analyzer/index.html',
  },
  {
    slug: 'topic-trend-analyzer',
    title: 'Topic Trend Analyzer',
    description: 'Analyze search trends for any topic. View trends over time, related queries, and regional interest.',
    icon: '📈',
    category: 'Analytics',
    isAI: true,
    path: '/tools/topic-trend-analyzer/index.html',
  },
  {
    slug: 'competitor-app-tracker',
    title: 'Competitor App Tracker',
    description: 'Track multiple competitor apps. Monitor ratings, reviews, prices, and compare features.',
    icon: '📊',
    category: 'Analytics',
    isAI: true,
    path: '/tools/competitor-app-tracker/index.html',
  },
  {
    slug: 'market-demographics-analyzer',
    title: 'Market Demographics Analyzer',
    description: 'Analyze target market demographics including age, gender, income, and geographic distribution.',
    icon: '📊',
    category: 'Analytics',
    isAI: false,
    path: '/tools/market-demographics-analyzer/index.html',
  },

  // SCRAPING & EXTRACTION
  {
    slug: 'meta-tag-extractor',
    title: 'Meta Tag Extractor',
    description: 'Extract all meta tags from any website. Get title, description, OG tags, and more for SEO.',
    icon: '🔍',
    category: 'Scraping',
    isAI: false,
    path: '/tools/meta-tag-extractor/index.html',
  },
  {
    slug: 'wordpress-content-extractor',
    title: 'WordPress Content Extractor',
    description: 'Extract recent posts from WordPress sites. Get title, date, author, and excerpt via REST API.',
    icon: '📝',
    category: 'Scraping',
    isAI: false,
    path: '/tools/wordpress-content-extractor/index.html',
  },
  {
    slug: 'list-data-extractor',
    title: 'List Data Extractor',
    description: 'Extract list items from HTML or URLs. Get data from ul, ol, and dl tags instantly.',
    icon: '📋',
    category: 'Scraping',
    isAI: false,
    path: '/tools/list-data-extractor/index.html',
  },
  {
    slug: 'wikipedia-content-extractor',
    title: 'Wikipedia Content Extractor',
    description: 'Extract full content from Wikipedia articles. Get summary, sections, and infobox data.',
    icon: '📖',
    category: 'Scraping',
    isAI: false,
    path: '/tools/wikipedia-content-extractor/index.html',
  },
  {
    slug: 'website-screenshot-tool',
    title: 'Website Screenshot Tool',
    description: 'Capture full-page screenshots of any website. Get desktop, tablet, and mobile views.',
    icon: '📸',
    category: 'Scraping',
    isAI: false,
    path: '/tools/website-screenshot-tool/index.html',
  },
  {
    slug: 'website-url-extractor',
    title: 'Website URL Extractor',
    description: 'Extract URLs directly from a website\'s pages. Discover all internal links.',
    icon: '🕸️',
    category: 'Scraping',
    isAI: false,
    path: '/tools/website-url-extractor/index.html',
  },

  // BUSINESS TOOLS
  {
    slug: 'b2b-lead-finder',
    title: 'B2B Lead Finder',
    description: 'Discover B2B leads by industry, company size, and location. Export leads as CSV.',
    icon: '💼',
    category: 'Business',
    isAI: true,
    path: '/tools/b2b-lead-finder/index.html',
  },
  {
    slug: 'university-finder',
    title: 'University Finder',
    description: 'Search universities by country, name, and state. Find university websites and details worldwide.',
    icon: '🎓',
    category: 'Business',
    isAI: false,
    path: '/tools/university-finder/index.html',
  },
  {
    slug: 'book-citation-generator',
    title: 'Book Citation Generator',
    description: 'Generate book citations in APA, MLA, and Chicago styles. Search by ISBN or title.',
    icon: '📚',
    category: 'Business',
    isAI: false,
    path: '/tools/book-citation-generator/index.html',
  },
  {
    slug: 'content-safety-checker',
    title: 'Content Safety Checker',
    description: 'Analyze text for profanity, toxicity, and readability. Perfect for content moderation.',
    icon: '🛡️',
    category: 'Business',
    isAI: false,
    path: '/tools/content-safety-checker/index.html',
  },
  {
    slug: 'landing-page-grader',
    title: 'Landing Page Grader',
    description: 'Score your landing page for conversion rate optimization using AI.',
    icon: '🎯',
    category: 'Business',
    isAI: true,
    path: '/tools/landing-page-grader/index.html',
  },
  {
    slug: 'lead-quality-checker',
    title: 'Lead Quality Checker',
    description: 'Analyze and score the quality of your incoming leads using AI.',
    icon: '⭐',
    category: 'Business',
    isAI: true,
    path: '/tools/lead-quality-checker/index.html',
  },
  {
    slug: 'fake-lead-probability-checker',
    title: 'Fake Lead Probability Checker',
    description: 'Identify bots and fake form submissions in your ad campaigns.',
    icon: '🕵️',
    category: 'Business',
    isAI: true,
    path: '/tools/fake-lead-probability-checker/index.html',
  },
  {
    slug: 'website-business-analyzer',
    title: 'Website Business Analyzer',
    description: 'Get instant business insights and firmographics from a URL.',
    icon: '📈',
    category: 'Business',
    isAI: true,
    path: '/tools/website-business-analyzer/index.html',
  },

  // AI POWERED TOOLS
  {
    slug: 'ai-answer-generator',
    title: 'AI Answer Generator',
    description: 'Generate comprehensive, fact-based answers to any complex question using advanced AI.',
    icon: '💡',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-answer-generator/index.html',
  },
  {
    slug: 'ai-email-response-generator',
    title: 'AI Email Response Generator',
    description: 'Draft professional email replies in seconds. Customizable tone and length.',
    icon: '📧',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-email-response-generator/index.html',
  },
  {
    slug: 'ai-letter-generator',
    title: 'AI Letter Generator',
    description: 'Draft formal cover letters, resignation letters, or client proposals with AI.',
    icon: '✉️',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-letter-generator/index.html',
  },
  {
    slug: 'ai-reply-generator',
    title: 'AI Reply Generator',
    description: 'Generate quick, context-aware replies for customer support and messaging.',
    icon: '💬',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-reply-generator/index.html',
  },
  {
    slug: 'ai-faq-generator',
    title: 'AI FAQ Generator',
    description: 'Generate Frequently Asked Questions automatically from your content.',
    icon: '❓',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-faq-generator/index.html',
  },
  {
    slug: 'ai-blog-title-generator',
    title: 'AI Blog Title Generator',
    description: 'Create catchy, SEO-friendly blog titles that drive clicks and engagement.',
    icon: '✍️',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-blog-title-generator/index.html',
  },
  {
    slug: 'ai-chatbot-name-generator',
    title: 'AI Chatbot Name Generator',
    description: 'Brainstorm creative, memorable names for your AI assistant or chatbot.',
    icon: '🤖',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chatbot-name-generator/index.html',
  },
  {
    slug: 'ai-saas-brand-name-generator',
    title: 'AI SaaS Brand Name Generator',
    description: 'Generate modern, available brand names for SaaS products and startups.',
    icon: '🚀',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-saas-brand-name-generator/index.html',
  },
  {
    slug: 'customer-service-script-generator',
    title: 'Customer Service Script Generator',
    description: 'Create professional scripts for various customer support scenarios.',
    icon: '🎧',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/customer-service-script-generator/index.html',
  },
  {
    slug: 'website-faq-generator',
    title: 'Website FAQ Generator',
    description: 'Generate schema-ready FAQs for your website automatically.',
    icon: '🕸️',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/website-faq-generator/index.html',
  },
  {
    slug: 'ai-chat-with-your-text-data',
    title: 'AI Chat with Your Text Data',
    description: 'Chat with your text documents using AI. Ask questions, get insights.',
    icon: '📝',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chat-with-your-text-data/index.html',
  },
  {
    slug: 'ai-chat-with-your-website-data',
    title: 'AI Chat with Your Website Data',
    description: 'Interact with scraped website content using natural language queries.',
    icon: '🌐',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chat-with-your-website-data/index.html',
  },
  {
    slug: 'ai-chat-with-your-document-data',
    title: 'AI Chat with Your Document Data',
    description: 'Upload documents and chat with them using AI. Extract insights instantly.',
    icon: '📄',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chat-with-your-document-data/index.html',
  },
  {
    slug: 'ai-chat-with-your-pdf-document-data',
    title: 'AI Chat with Your PDF Data',
    description: 'Chat with PDF files using AI. Ask questions, summarize, extract key points.',
    icon: '📕',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chat-with-your-pdf-document-data/index.html',
  },
  {
    slug: 'ai-chat-with-your-word-document-data',
    title: 'AI Chat with Your Word Data',
    description: 'Chat with DOCX files using AI. Get summaries and answers from Word documents.',
    icon: '📘',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chat-with-your-word-document-data/index.html',
  },
  {
    slug: 'ai-chatbot-conversation-analysis',
    title: 'AI Chatbot Conversation Analysis',
    description: 'Analyze and optimize chatbot dialogue flows using AI insights.',
    icon: '💬',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-chatbot-conversation-analysis/index.html',
  },
  {
    slug: 'best-ai-prompt-generator',
    title: 'Best AI Prompt Generator',
    description: 'Generate optimized prompts for AI models. Get better results every time.',
    icon: '✨',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/best-ai-prompt-generator/index.html',
  },
  {
    slug: 'ai-prompt-optimizer',
    title: 'AI Prompt Optimizer',
    description: 'Refine your AI prompts for better, more consistent results.',
    icon: '🎯',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/ai-prompt-optimizer/index.html',
  },
  {
    slug: 'pdf-to-faq-generator',
    title: 'PDF to FAQ Generator',
    description: 'Extract insights from PDFs and create FAQ sections automatically.',
    icon: '📄',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/pdf-to-faq-generator/index.html',
  },
  {
    slug: 'docx-to-faq-generator',
    title: 'DOCX to FAQ Generator',
    description: 'Generate FAQs from Word documents automatically using AI.',
    icon: '📝',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/docx-to-faq-generator/index.html',
  },
  {
    slug: 'text-to-faq-generator',
    title: 'Text to FAQ Generator',
    description: 'Generate FAQs from plain text content using AI.',
    icon: '❓',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/text-to-faq-generator/index.html',
  },
  {
    slug: 'csv-to-faq-generator',
    title: 'CSV to FAQ Generator',
    description: 'Generate FAQs from CSV data automatically using AI.',
    icon: '❓',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/csv-to-faq-generator/index.html',
  },
  {
    slug: 'json-to-faq-generator',
    title: 'JSON to FAQ Generator',
    description: 'Generate FAQs from JSON data automatically using AI.',
    icon: '❓',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/json-to-faq-generator/index.html',
  },
  {
    slug: 'html-to-faq-generator',
    title: 'HTML to FAQ Generator',
    description: 'Extract FAQs from raw HTML data using AI analysis.',
    icon: '🌐',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/html-to-faq-generator/index.html',
  },
  {
    slug: 'google-docs-to-faq-generator',
    title: 'Google Docs to FAQ Generator',
    description: 'Turn Google Docs into clean FAQ formats using AI.',
    icon: '📗',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/google-docs-to-faq-generator/index.html',
  },
  {
    slug: 'notion-to-faq-generator',
    title: 'Notion to FAQ Generator',
    description: 'Convert Notion pages into structured FAQs using AI.',
    icon: '📓',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/notion-to-faq-generator/index.html',
  },
  {
    slug: 'webpage-to-faq-generator',
    title: 'Webpage to FAQ Generator',
    description: 'Turn any webpage content into an FAQ section using AI.',
    icon: '🖥️',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/webpage-to-faq-generator/index.html',
  },
  {
    slug: 'website-to-faq-generator',
    title: 'Website to FAQ Generator',
    description: 'Generate FAQs from website content using AI analysis.',
    icon: '❓',
    category: 'AI Tools',
    isAI: true,
    path: '/tools/website-to-faq-generator/index.html',
  },
  // NEW TEXT TOOLS
  {
    slug: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs. Get reading time and text statistics.',
    icon: '📊',
    category: 'Text Tools',
    isAI: false,
    path: '/tools/word-counter/index.html',
  },
  {
    slug: 'convert-case',
    title: 'Convert Case',
    description: 'Convert text to uppercase, lowercase, title case, camelCase, and 8+ other formats.',
    icon: '🔤',
    category: 'Text Tools',
    isAI: false,
    path: '/tools/convert-case/index.html',
  },
  {
    slug: 'json-formatter',
    title: 'JSON Formatter & Beautifier',
    description: 'Format, validate, and minify JSON data. Syntax highlighting and error detection.',
    icon: '📝',
    category: 'Developer Tools',
    isAI: false,
    path: '/tools/json-formatter/index.html',
  },
];

export const categories: string[] = [
  'Most Popular',
  'Utility',
  'Calculators',
  'Sitemap',
  'Converters',
  'Analytics',
  'Scraping',
  'Business',
  'Text Tools',
  'Developer Tools',
  'AI Tools',
];

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getPopularTools(): Tool[] {
  return tools.filter((tool) => tool.isPopular);
}

export function getAITools(): Tool[] {
  return tools.filter((tool) => tool.isAI);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    (tool) =>
      tool.title.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery)
  );
}

export function getRelatedTools(tool: Tool, limit: number = 4): Tool[] {
  return tools
    .filter((t) => t.category === tool.category && t.slug !== tool.slug)
    .slice(0, limit);
}

// New Text Tools
export function getTextTools(): Tool[] {
  return tools.filter((tool) => tool.category === 'Text Tools');
}

// New Developer Tools
export function getDeveloperTools(): Tool[] {
  return tools.filter((tool) => tool.category === 'Developer Tools');
}
